### ISSUE TITLE
Direct Permission

### ISSUE THREAD

**Issue by daniyalishaq** [LaravelDaily/QuickAdminPanel-Material-Dashboard#7]
What I want is, if somebody has a role User, there should be a way for Admin to assign different permissions to different users with the role User.

Tom was assigned the user role and he can Create and Update something
Another user with the user role created by  Admin

Ben was assigned the user role and he can Create, Read, Update, Delete something

Now you can clearly see the difference between Tom and Ben. They have the same role user but with different sets of permissions.

Now, I've done the DB side. the issue I'm facing is in the Auth Gates 

`foreach ($user_permissions as $user_permission) {
                foreach ($user_permission->permissions as $permissions) {
                    $user_permissions_array[$permissions->title][] = $user_permission->id;
                }
            }`

`foreach ($user_permissions_array as $title => $user_permissions) {
                Gate::define($title, function (\App\User $user) use ($user_permissions) {
                    return count(array_intersect($user->roles->pluck('id')->toArray(), $user_permissions)) > 0 ;
                });`

When I assign direct permission to the user of 'Role' access for example then it stops showing for admin but admin has all permissions.

**Comment by PovilasKorop** [comment]
@daniyalishaq sorry, we don't provide personal support with customizations of this free demo project.
